### ISSUE TITLE
why accessing \device\cdrom?

### ISSUE THREAD

**Issue by ghost** [DavidXanatos/priv10#22]
* W10 Pro x_64 v1909 b18363.476
* priv10 v0.60
___
For what purpose the app needs such access?

![Annotation 2019-11-30 123406](https://user-images.githubusercontent.com/13611490/69899979-be16a080-1365-11ea-9962-b87f06c839c3.png)

**Comment by DavidXanatos** [comment]
The function GetDriveLetter(string longPath) queries all drives in the system to resolve paths like:
\device\harddiskvolume2 -> C:

I have no idea why that would trigger a security warning with windows defender.

**Comment by CHEF-KOCH** [comment]
@n8v8R 
You can exclude the `PrivateWin10.exe` from WD, which I would do due to performance reasons. The app is FOSS and does not connect to the internet unless you use the DNS proxy (blocking mechanism) which is optional.

I in general advise to work with exclusions in WD, because background processes which running constantly but are never connected to the net otherwise causing possible "lags" since WD often gets triggered and "re-scans" the app a dozen times a day for basically nothing.

I submitted the project to MS, and labeled it as "false/positive". [GetDriveLetter](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-vds/c1d4171f-5e64-4f44-9c3b-925566ec0c18) triggers WD because you can also use it for "unknown" partition iin the disk.
